### PR TITLE
Update Plugin.cs

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
haunted mm

**Comment by fchb1239** [comment]
that isn't how you add it lol

also you can just say "hey ples add haunted mod menu support"
and even this i was gonna do that at some point D:

**Comment by ghost** [comment]
sorry i realised that I just rushed and didnt test it

**Comment by ghost** [comment]
and i dont know how to contact you

**Comment by ghost** [comment]
yeah, but I'm dumb

**Comment by ghost** [comment]
oh, and how did you learn to code

**Pull request closed without merging**
